Repository Team4LinkShop/Team4LinkShop, pull requests merged in 2024-10, with the labels that each got.

#16 [이수지][#14] PR 템플릿 미작동 문제 develop브랜치 수정
  .github/PULL_REQUEST_TEMPLET.md
Labels: documentation

#26 [이수지][#24] 메타태그에서 상점 대표 이미지 불러오기
  index.html
  src/App.jsx
  src/api/likes.js
  src/api/link-shop.js
  src/components/ExtensionMenu.jsx
  src/components/LikeButton.jsx
  src/components/ProfileDropDown.jsx
  src/components/ShareButton.jsx
  src/hooks/useMetaImage.js
  src/main.jsx
  src/pages/ProfileDetailPage.jsx
Labels: enhancement

#29 [이수지][#25] 상세 페이지 반응형 추가 및 리펙토링
  package-lock.json
  package.json
  src/App.jsx
  src/api/likes.js
  src/api/link-shop.js
  src/components/LikeButton.jsx
  src/hooks/useMetaImage.js
  src/main.jsx
  src/pages/ProfileDetailPage.jsx
  src/utils/formatPrice.js
Labels: duplicate, enhancement

#28 [이영찬][#10] 완료모달창
  src/components/CompleteButton.jsx
Labels: enhancement
