Repository Team4LinkShop/Team4LinkShop, pull requests merged in 2024-09, with the labels that each got.

#2 [이수지][#1] 프로젝트 초기셋팅 및 필수 라이브러리 설치
  .github/pull-request-templet.md
  .github/workflows/ci.yml
  .gitignore
  .prettierignore
  .prettierrc.json
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/api/readme.md
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard-SemiBold.woff
  src/assets/fonts/Pretendard-SemiBold.woff2
  src/assets/fonts/readme.md
  src/assets/readme.md
  src/components/common/readme.md
  src/components/readme.md
  src/constants/readme.md
  src/hooks/readme.md
  src/index.css
  src/main.jsx
  src/pages/readme.md
  src/store/readme.md
  src/styles/readme.md
  src/utils/readme.md
  vite.config.js
Labels: documentation, enhancement

#6 [이수지][#5] emotion babel 셋팅
  package.json
  vite.config.js
Labels: documentation

#7 [이수지][#3] 프로필 상세페이지 퍼블리싱
  src/assets/bg-market-roof.svg
  src/assets/ic-blank-heart.svg
  src/assets/ic-full-heart.svg
  src/assets/ic-left-arrow.svg
  src/assets/ic-meatball.svg
  src/assets/ic-share.svg
  src/assets/mock-profile-img.jpg
  src/main.jsx
  src/pages/ProfileDetailPage.jsx
Labels: enhancement

#11 [모수진][#4] 로고 컴포넌트, 샵리스트 컴포넌트 추가
  src/components/common/BtnCreate.jsx
  src/components/common/Logo.jsx
  src/pages/ShopList.jsx
Labels: enhancement
